/*STANDARD INPUT OUTPUT SYSTEM*/
/*COUT<< IS USED FOR OUTPUT OF ANY THING IN C PLATFORM
& CIN>>  IS USED FOR INPUT  OF ANY THING IN C PLATFORM*/
#include<iostream.h>
#include<conio.h>
void main()
{
int a,b;
cout<<"++++++++++SAURABH IS OUTPUT NOW++++++++";//output//
cout<<"***************************************";//output//
cin>>a;//input//
cin>>b;//input//
getch();
}
/*In this program you can see 2 output & 2 times input*/