#include<iostream.h>
#include<conio.h>
void main()
{
int a,b,c,d,e;
clrscr();
cout<<"Enter no:";
cin>>a;
cout<<"Enter no:";
cin>>b;
if(a==b)
{
cout<<"\n\nA & B both are equalls";
}
if(a!=b)
{
cout<<"\n\nA & B are not equall";
}
if(a>b)
{
cout<<"\n\nA is greater than B";
}
if(a<b)
{
cout<<"\n\nB is greater than A";
}
if(a>=b)
{
cout<<"\n\nA is greater & equal to B";
}
if(a<=b)
{
cout<<"\n\nA is less than equall to B";
}
getch();
}